# This is a basic workflow to help you get started with Actions

name: Microsoft Graph Query

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Azure AD
        run: |
          $Password = ConvertTo-SecureString '${{ secrets.CLIENTSECRET }}' -AsPlainText -Force
          $Credential = New-Object System.Management.Automation.PSCredential -ArgumentList('${{ secrets.APPID }}',$Password)
          Connect-AzAccount -ServicePrincipal -Tenant ${{ secrets.TENANTID }} -Credential $Credential
        shell: pwsh
