# This is a basic workflow to help you get started with Actions

name: Microsoft Graph Query

on:
  schedule:
    #- cron: '*/5 * * * *' # run every 5 minutes
    - cron: '0 6 * * * *' # run at 06:00, daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v3
      
      - name: Authenticate to Azure AD
        run: |
          $ApplicationId = '${{ secrets.APPID }}'
          $TenantId = '${{ secrets.TENANTID }}'
          $ClientSecret = '${{ secrets.CLIENTSECRET }}'
          $Body = @{
            Grant_Type    = 'client_credentials'
            Scope         = 'https://graph.microsoft.com/.default'
            Client_Id     = $ApplicationId
            Client_Secret = $ClientSecret
          }
          $LoginUri = "https://login.microsoftonline.com/$TenantId/oauth2/v2.0/token"
          $ConnectGraph = Invoke-RestMethod -Uri $LoginUri -Method Post -Body $Body
          $Token = $ConnectGraph.access_token
          $TeamsReportUri = "https://graph.microsoft.com/beta/reports/getTeamsUserActivityUserDetail(period='D7')"
          Invoke-RestMethod -Headers @{Authorization = "Bearer ${Token}"} -Uri $TeamsReportUri -Method Get
